/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsMarketIdRouteImport } from './routes/markets_.$marketId'
import { Route as MarketIdBuilderRouteImport } from './routes/$marketId.builder'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/markets_/$marketId',
  path: '/markets/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIdBuilderRoute = MarketIdBuilderRouteImport.update({
  id: '/$marketId/builder',
  path: '/$marketId/builder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/markets': typeof MarketsRoute
  '/settings': typeof SettingsRoute
  '/$marketId/builder': typeof MarketIdBuilderRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/markets': typeof MarketsRoute
  '/settings': typeof SettingsRoute
  '/$marketId/builder': typeof MarketIdBuilderRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/markets': typeof MarketsRoute
  '/settings': typeof SettingsRoute
  '/$marketId/builder': typeof MarketIdBuilderRoute
  '/markets_/$marketId': typeof MarketsMarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/builder'
    | '/dashboard'
    | '/markets'
    | '/settings'
    | '/$marketId/builder'
    | '/markets/$marketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/builder'
    | '/dashboard'
    | '/markets'
    | '/settings'
    | '/$marketId/builder'
    | '/markets/$marketId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/builder'
    | '/dashboard'
    | '/markets'
    | '/settings'
    | '/$marketId/builder'
    | '/markets_/$marketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuilderRoute: typeof BuilderRoute
  DashboardRoute: typeof DashboardRoute
  MarketsRoute: typeof MarketsRoute
  SettingsRoute: typeof SettingsRoute
  MarketIdBuilderRoute: typeof MarketIdBuilderRoute
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets_/$marketId': {
      id: '/markets_/$marketId'
      path: '/markets/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$marketId/builder': {
      id: '/$marketId/builder'
      path: '/$marketId/builder'
      fullPath: '/$marketId/builder'
      preLoaderRoute: typeof MarketIdBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuilderRoute: BuilderRoute,
  DashboardRoute: DashboardRoute,
  MarketsRoute: MarketsRoute,
  SettingsRoute: SettingsRoute,
  MarketIdBuilderRoute: MarketIdBuilderRoute,
  MarketsMarketIdRoute: MarketsMarketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
